wf-background: allow seamless background updates
WayfireWM/wf-shell pull request #200
Opened 2023-12-04 15:00 UTC by lcolitti

This adds two minor features to wf-background:
- The ability to set the fade duration (including to zero).
- The ability to update/cycle the background by sending SIGHUP.

Together, these can be allowed to implement seamless background
updates of slow-moving scenes. As an example, my background is an
image recalculated by xplanet every few minutes. I run xplanet
with a post_command that sends a SIGHUP to wf-background.
With a fade duration of zero, wf-background just replaces the
image imperceptibly, with no fading and no flicker.

2023-12-04 15:11 UTC, ammen99 requested changes
Overall LGTM, there are two issues which need resolving first.

2023-12-04 15:11 UTC, ammen99 commented on metadata/background.xml.in
> +    <option name="fade_duration" type="int">
Indentation seems off in this file (probably tabs vs spaces)

2023-12-04 15:11 UTC, ammen99 commented on src/background/background.cpp
> +    g_unix_signal_add(SIGHUP, sighup_handler, this);
I am not sure whether SIGHUP is the proper signal here - SIGHUP means "Hangup detected on controlling terminal or death of controlling process". We can use SIGUSR1 instead, which is specifically left for private use by programs.

2023-12-05 11:49 UTC, lcolitti commented on metadata/background.xml.in
> +    <option name="fade_duration" type="int">
Oops, yes. Fixed.

2023-12-05 12:26 UTC, ammen99 approved these changes
LGTM, thanks!

2023-12-07 10:34 UTC, lcolitti commented on src/background/background.hpp
> +    static int sigusr1_handler(void *thiz)
"this" is a reserved word and the code won't compile. I used "thiz" because it looks like "this" and makes it clear that this is a pointer to the class instance.

2023-12-07 10:48 UTC, lcolitti commented on src/background/background.hpp
> +        g_unix_signal_add(SIGUSR1, sigusr1_handler, thiz);
The handler has to be reinstalled after the signal is handled, or it only works once. Looks like the signal handling code in glib resets the signal handler once it fires:

[pid 1131077] --- SIGUSR1 {si_signo=SIGUSR1, si_code=SI_USER, si_pid=1131111, si_uid=xxxxx} ---
[pid 1131077] rt_sigreturn({mask=[]})   = -1 EINTR (Interrupted system call)
Loaded /usr/share/backgrounds/xplanet/xplanet.png
[pid 1131077] rt_sigaction(SIGUSR1, {sa_handler=SIG_DFL, sa_mask=[], sa_flags=SA_RESTORER, sa_restorer=0x7f5e1605a510}, NULL, 8) = 0

2023-12-07 10:49 UTC, lcolitti commented on src/background/background.hpp
> +        std::cout << "Got SIGUSR1, reloading background" << std::endl;
Removed.

2023-12-07 11:31 UTC, lcolitti commented on src/background/background.cpp
> +    g_unix_signal_add(SIGUSR1, sigusr1_handler, this);
Ouch. The patch registered one signal handler per output, but it never unregistered it, so if a signal was handled after an output was received, it would crash. :-1: 

Rewritten to use the same signal handler for all outputs.

2023-12-07 12:19 UTC, soreau commented on src/background/background.hpp
> +    bool change_background(int timer);
Since `timer` is unused in this function, it should be safe to remove as an argument.

2023-12-07 12:22 UTC, soreau commented on src/background/background.hpp
> +    WfOption<int> fade_duration{"background/fade_duration"};
Optional: Group this option with `fade` variable above, since they work together.

2024-02-13 05:44 UTC, lcolitti commented
@soreau I think the comment you had was already resolved in the most recent push. Could you take another look?

2024-02-13 09:23 UTC, soreau approved these changes

2024-02-13 10:34 UTC, ammen99 commented
Thanks again :)

2024-02-13 10:34 UTC, merged