Add "Fill and Crop" option for wf-background
WayfireWM/wf-shell pull request #58
Opened 2020-08-14 15:14 UTC by CheesecakeCG

This is my first time ever making a PR, sorry in advance if I messed something up!

I added an option that makes the wallpaper fit the height of the screen and crop the sides to preserve the aspect ratio. 
I haven't tested this on anything else besides a single 5:4 monitor with 16:9 and 21:9 wallpapers, but it works in that case. 

I also realized while writing this that it doesn't crop vertical wallpapers correctly, making the name "Fill and Crop" somewhat misleading. I'll fix that ASAP.

2020-08-16 00:49 UTC, CheesecakeCG commented on src/background/background.cpp
>      }
I'm sure there's a better way to check what the available options are, but I could not find it.

2020-08-16 08:04 UTC, ammen99 commented on src/background/background.cpp
>      }
Not really, wf-config doesn't support enum types yet (if I understand you correctly)

2020-08-16 13:48 UTC, CheesecakeCG commented on src/background/background.cpp
>      }
Yeah, that's what I meant! Thanks!

2020-08-25 14:42 UTC, soreau commented
Does your fill-and-crop mode work for images of random sizes, i.e. not matching width or height of the output? Here, when I try a randomly sized images, the mode doesn't work very well. Typically, the bottom half of the image is cut off and the top isn't at all. Also, when I select other modes that set offset as a result of image not being same dimensions as output, and then switch back to fill-and-crop, the offset isn't reset, so then all of the images are offset by whatever the last image was for the other mode.

2020-09-11 17:57 UTC, CheesecakeCG commented
> then all of the images are offset by whatever the last image was for the other mode.
I'd accidentally put an "else" in right before it would have set the offset for new image. Oops.

> Does your fill-and-crop mode work for images of random sizes, i.e. not matching width or height of the output?
Yes, it does now at least. It works on vertical screens too.

2020-11-08 16:58 UTC, ammen99 requested changes
Sorry for the delay, I did not get a notification when you requested my review.

See the individual comments.

2020-11-08 16:58 UTC, ammen99 commented on wf-shell.ini.example
> +# Whether to scale images or preserve background ratio and fit width
As far as I understand, the `preserve_aspect` option is no longer valid, so you should remove it from the example config file.

2020-11-08 16:58 UTC, ammen99 commented on src/background/background.cpp
> +    float screen_aspect_ratio = (float) width / height;
Indentation seems to be quite broken on a lot of places. Use spaces only.

2020-11-08 16:58 UTC, ammen99 commented on src/background/background.cpp
> +    float screen_aspect_ratio = (float) width / height;
And add 4 spaces for each new indentation level.

2020-11-08 16:58 UTC, ammen99 commented on src/background/background.cpp
> +    if (!fill_and_crop_string.compare(background_fill_mode))
I would rather do these `if/else if/else` guards one time, and potentially have `gdk::create_from_file` called in each of these branches with the correct parameters, special casing here doesn't look very good.

2021-09-06 15:32 UTC, botiapa commented
Sorry for the bump, but any progress on this? IMHO this is quite an important feature, and I'd very much like to see it merged if ready.

2024-04-03 05:02 UTC, ammen99 commented
Closing in favor of #226

2024-04-03 05:02 UTC, closed without merging